// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pullRequest/create": {
            "post": {
                "description": "Создает новый pull request и автоматически назначает до двух активных ревьюверов из команды автора",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PullRequests"
                ],
                "summary": "Создать PR и автоматически назначить до 2 ревьюверов из команды автора",
                "parameters": [
                    {
                        "description": "Данные PR",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.PostPullRequestCreateJSONBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "PR создан",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Автор/команда не найдены",
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "PR уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pullRequest/merge": {
            "post": {
                "description": "Изменяет статус PR на MERGED. Операция идемпотентна - повторный вызов не приводит к ошибке",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PullRequests"
                ],
                "summary": "Пометить PR как MERGED (идемпотентная операция)",
                "parameters": [
                    {
                        "description": "Данные PR",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.PostPullRequestMergeJSONBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PR в состоянии MERGED",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "PR не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pullRequest/reassign": {
            "post": {
                "description": "Заменяет одного ревьювера на случайного активного участника из команды заменяемого ревьювера",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PullRequests"
                ],
                "summary": "Переназначить конкретного ревьювера на другого из его команды",
                "parameters": [
                    {
                        "description": "Данные для переназначения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.PostPullRequestReassignJSONBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Переназначение выполнено",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "PR или пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Нарушение доменных правил переназначения",
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team/add": {
            "post": {
                "description": "Создает новую команду и обновляет/создает пользователей",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Создать команду с участниками (создаёт/обновляет пользователей)",
                "parameters": [
                    {
                        "description": "Данные команды",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.Team"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Команда создана",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Команда уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team/get": {
            "get": {
                "description": "Возвращает информацию о команде и её участниках",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Получить команду с участниками",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальное имя команды",
                        "name": "team_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Объект команды",
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.Team"
                        }
                    }
                }
            }
        },
        "/users/getReview": {
            "get": {
                "description": "Возвращает список pull requests, назначенных пользователю на ревью",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Получить PR'ы, где пользователь назначен ревьювером",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список PR'ов пользователя",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/setIsActive": {
            "post": {
                "description": "Изменяет статус активности пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Установить флаг активности пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.PostUsersSetIsActiveJSONBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённый пользователь",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_PaulLocust_Avito-review_internal_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.ErrorResponseErrorCode"
                        },
                        "message": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "github_com_PaulLocust_Avito-review_internal_dto.ErrorResponseErrorCode": {
            "type": "string",
            "enum": [
                "NO_CANDIDATE",
                "NOT_ASSIGNED",
                "NOT_FOUND",
                "PR_EXISTS",
                "PR_MERGED",
                "TEAM_EXISTS"
            ],
            "x-enum-varnames": [
                "NOCANDIDATE",
                "NOTASSIGNED",
                "NOTFOUND",
                "PREXISTS",
                "PRMERGED",
                "TEAMEXISTS"
            ]
        },
        "github_com_PaulLocust_Avito-review_internal_dto.PostPullRequestCreateJSONBody": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "pull_request_id": {
                    "type": "string"
                },
                "pull_request_name": {
                    "type": "string"
                }
            }
        },
        "github_com_PaulLocust_Avito-review_internal_dto.PostPullRequestMergeJSONBody": {
            "type": "object",
            "properties": {
                "pull_request_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PaulLocust_Avito-review_internal_dto.PostPullRequestReassignJSONBody": {
            "type": "object",
            "properties": {
                "old_user_id": {
                    "type": "string"
                },
                "pull_request_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PaulLocust_Avito-review_internal_dto.PostUsersSetIsActiveJSONBody": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PaulLocust_Avito-review_internal_dto.Team": {
            "type": "object",
            "properties": {
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PaulLocust_Avito-review_internal_dto.TeamMember"
                    }
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "github_com_PaulLocust_Avito-review_internal_dto.TeamMember": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PR Reviewer Assignment Service",
	Description:      "Сервис назначения ревьюверов для Pull Request'ов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
